version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: planetscale/pscale-proxy:latest
    ports:
      - "3306:3306"
    environment:
      - PSCALE_DATABASE_URL=${DATABASE_URL}
    command: pscale-proxy connect ${DATABASE_NAME} --port 3306

  ai_runner:
    build:
      context: ./ai-runner
      dockerfile: Dockerfile
    volumes:
      - ./ai-runner/sample_ai:/app/ai_scripts
    environment:
      - API_URL=http://backend:3001
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    depends_on:
      - backend 
